In [1]:
import numpy as np
import time

In [2]:
arr = np.array([12,2,4,4])

In [3]:
arr

array([12,  2,  4,  4])

In [4]:
size = 10000000

l1 = range(size)
l2 = range(size)

n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took: ", (time.time()-start)*1000 )

start = time.time()
result = n1+n2
print("Numpy took: ", (time.time()-start)*1000)

Python list took:  916.9018268585205
Numpy took:  196.5467929840088


In [5]:
# single dimension array
a = np.array([1,0,0])
a.ndim

1

In [6]:
#double dimension 
a = np.array([[1,2,3],[1,5,3]])
print (a)
print("dimension:", a.ndim)

[[1 2 3]
 [1 5 3]]
dimension: 2


In [7]:
#datatype
a = np.array([[1,2,3],[1,5,3]], dtype=np.int32)
a.dtype


dtype('int32')

In [8]:
a.size

6

In [9]:
a.shape

(2, 3)

In [10]:
arr = np.arange(1,5).reshape(4,1)
arr

array([[1],
       [2],
       [3],
       [4]])

In [11]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [12]:
a

array([[1, 2, 3],
       [1, 5, 3]], dtype=int32)

In [13]:
a = a.ravel() #make it a flatten array
a

array([1, 2, 3, 1, 5, 3], dtype=int32)

In [14]:
#mathematical function
print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.sum(axis = 0)) #column


1
4
10
[10]


In [15]:
np.std(arr) # standard deviation

1.118033988749895

In [16]:
a = np.array( [[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [17]:
print(a,b)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [18]:
a+b

array([[ 6,  8],
       [10, 12]])

In [19]:
a*b

array([[ 5, 12],
       [21, 32]])

In [20]:
a.dot(b) #matrices product

array([[19, 22],
       [43, 50]])

In [21]:
# Slicing
a = np.array([[6,77,7],[5,6,7],[5,6,7],[5,6,7]])
print(a)

[[ 6 77  7]
 [ 5  6  7]
 [ 5  6  7]
 [ 5  6  7]]


In [22]:
a[0:3,1]

array([77,  6,  6])

In [23]:
a[2:4,1:]

array([[6, 7],
       [6, 7]])

In [24]:
#Iteration

In [25]:
a

array([[ 6, 77,  7],
       [ 5,  6,  7],
       [ 5,  6,  7],
       [ 5,  6,  7]])

In [26]:
for row in a:
    print (row)

[ 6 77  7]
[5 6 7]
[5 6 7]
[5 6 7]


In [27]:
for cell in a.flat:
    print (cell)

6
77
7
5
6
7
5
6
7
5
6
7


In [28]:
b

array([[5, 6],
       [7, 8]])

In [29]:
c = np.arange(4).reshape(2,2)

In [30]:
c

array([[0, 1],
       [2, 3]])

In [31]:
np.vstack((b,c))

array([[5, 6],
       [7, 8],
       [0, 1],
       [2, 3]])

In [32]:
np.hstack((b,c))


array([[5, 6, 0, 1],
       [7, 8, 2, 3]])

In [33]:
#splitting
arr = np.arange(30).reshape(2,15)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [34]:
hsplittt = np.hsplit(arr,3)

In [35]:
hsplittt[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [36]:
vspl = np.vsplit(arr,2)

In [37]:
vspl[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [38]:
r = np.arange(12).reshape(3,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
b = r > 4

In [44]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
r[b]

array([ 5,  6,  7,  8,  9, 10, 11])