In [5]:
import numpy as np
import time

In [3]:
arr = np.array([12,2,4,4])

In [4]:
arr

array([12,  2,  4,  4])

In [8]:
size = 10000000

l1 = range(size)
l2 = range(size)

n1 = np.arange(size)
n2 = np.arange(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took: ", (time.time()-start)*1000 )

start = time.time()
result = n1+n2
print("Numpy took: ", (time.time()-start)*1000)

Python list took:  1695.896863937378
Numpy took:  1114.1462326049805


In [9]:
# single dimension array
a = np.array([1,0,0])
a.ndim

1

In [11]:
#double dimension 
a = np.array([[1,2,3],[1,5,3]])
print (a)
print("dimension:", a.ndim)

[[1 2 3]
 [1 5 3]]
dimension: 2


In [13]:
#datatype
a = np.array([[1,2,3],[1,5,3]], dtype=np.int32)
a.dtype


dtype('int32')

In [14]:
a.size

6

In [15]:
a.shape

(2, 3)

In [24]:
arr = np.arange(1,5).reshape(4,1)
arr

array([[1],
       [2],
       [3],
       [4]])

In [26]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [27]:
a

array([[1, 2, 3],
       [1, 5, 3]], dtype=int32)

In [28]:
a = a.ravel() #make it a flatten array
a

array([1, 2, 3, 1, 5, 3], dtype=int32)

In [34]:
#mathematical function
print(arr.min())
print(arr.max())
print(arr.sum())
print(arr.sum(axis = 0)) #column


1
4
10
[10]


In [36]:
np.std(arr) # standard deviation

1.118033988749895

In [37]:
a = np.array( [[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [38]:
print(a,b)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]


In [39]:
a+b

array([[ 6,  8],
       [10, 12]])

In [40]:
a*b

array([[ 5, 12],
       [21, 32]])

In [41]:
a.dot(b) #matrices product

array([[19, 22],
       [43, 50]])